name: Deploy to itch.io

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-itch:
    strategy:
        matrix:
            include:
                - package: win
                  channel: win

                - package: mac
                  channel: osx

                - package: linux
                  channel: linux

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          clean: true

      - name: Publish to itch.io
        uses: KagariSoft/renpy-ci@v1
        with:
          renpy-version: '8.5.3'
          game-dir: '.'
          package: ${{ matrix.package }}
          publish-itch: 'true'
          itch-target: ${{ secrets.BUTLER_USER_SLASH_GAME }}
          itch-channel: ${{ matrix.channel }}
          butler-key: ${{ secrets.BUTLER_API_KEY }}

      - name: Install Ren'py web support
        run: |
          wget https://www.renpy.org/dl/release/renpy-8.5.3-web.zip
          unzip -q renpy-8.5.3-web.zip -d "$RENPY_SDK_DIR"

      - name: Build web
        run: |
          cd "$RENPY_SDK_DIR"
          ./renpy.sh launcher web_build "$GITHUB_WORKSPACE" \
          --destination "$RENPY_DIST_PATH/web"

      - name: Upload web build
        run: |
          butler push \
          $RENPY_DIST_PATH/web/Dramaturgy-1.0-web" \
          ${{ secrets.BUTLER_USER_SLASH_GAME }}:html5
        
        env:
            BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}